language: android
dist: trusty
jdk: oraclejdk8

branches:
  only:
    - master

script: "./gradlew clean assembleDebug"

env:
  global:
    - ANDROID_API=26
    - ANDROID_BUILD_TOOLS=28.0.3
    - HIGHEST_API=29
    - LOWEST_API=14

android:
  components:
      - tools
      - platform-tools
      - build-tools-$ANDROID_BUILD_TOOLS
      - android-$ANDROID_API
      - extra-android-m2repository
      - sys-img-x86-android-$HIGHEST_API
      - sys-img-x86-android-$LOWEST_API
  licenses:
      - android-sdk-preview-license-d099d938
      - android-sdk-license-.+
